// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfmg7QM0-gkIylyznPWZb91XOjbteufCs',
    appId: '1:782955979534:web:7aab7ed2fa0a1e06fd2d5f',
    messagingSenderId: '782955979534',
    projectId: 'fresh-farm-852c8',
    authDomain: 'fresh-farm-852c8.firebaseapp.com',
    storageBucket: 'fresh-farm-852c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVltYPG0hdj9ptXc0rwvjw14GoB7Oeq6E',
    appId: '1:782955979534:android:91abadb7a44e3a43fd2d5f',
    messagingSenderId: '782955979534',
    projectId: 'fresh-farm-852c8',
    storageBucket: 'fresh-farm-852c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQPketkriVkpVVJqQWxl92IPBHZ2qfO9I',
    appId: '1:782955979534:ios:8d87d253b841b3aafd2d5f',
    messagingSenderId: '782955979534',
    projectId: 'fresh-farm-852c8',
    storageBucket: 'fresh-farm-852c8.appspot.com',
    iosBundleId: 'com.example.freshFarm',
  );
}
